enum STATUS {
  INACTIVE
  LEFT
  BUSY
  AVAILABLE
}

type User {
  id: ID
  alias: String
  presence: Presence
}

type Presence {
  id: ID
  status: String
  user: User
}

type Query {
  users: [User]
  presences: [Presence]
}

input PresenceInput {
  id: ID
  status: String
}

input UserInput {
  id: ID
  alias: String
}

type Mutation {
  join(input: UserInput): User
  leave(id: ID): User
  toggle(input: PresenceInput): User
}

type Subscription {
  onPresence: User
}